library("reshape2")
library("ggplot2")
library("dplyr")

# Most common time series libraries
library("dlm")
library("forecast")
library("lubridate")
library("tseries")
library("xts") 
library("zoo")
library("expsmooth")
library("seewave")
library("fpp")
library("TSA")
library("astsa")
library("ggfortify")
library("EMD")
library("ggpubr")
library("gridExtra")
library("gsignal")
library("pracma")
library("SlidingWindows")
library("photobiology")
library("doBy")
library("SlidingWindows")
library("pracma")
library("pracma")
library("caret")
library("pracma")
library("ggplot2")

# Hadley Wickham's tidyverse universe
library("tidyverse")

# To load a library, use the function
library("xts")
